var b=b||{};b.global=this;b.exportPath_=function(a,c,d){a=a.split(".");d=d||b.global;a[0]in d||!d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===c?d=d[e]?d[e]:d[e]={}:d[e]=c};b.define=function(a,c){b.exportPath_(a,c)};b.DEBUG=!0;b.LOCALE="es";b.TRUSTED_SITE=!0;b.provide=function(a){b.exportPath_(a)};b.setTestOnly=function(a){if(!b.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
b.getObjectByName=function(a,c){for(var d=a.split("."),e=c||b.global,f;f=d.shift();)if(b.isDefAndNotNull(e[f]))e=e[f];else return null;return e};b.globalize=function(a,c){var d=c||b.global,e;for(e in a)d[e]=a[e]};b.addDependency=function(a,c,d){if(b.DEPENDENCIES_ENABLED){var e;a=a.replace(/\\/g,"/");for(var f=b.dependencies_,h=0;e=c[h];h++)f.nameToPath[e]=a,a in f.pathToNames||(f.pathToNames[a]={}),f.pathToNames[a][e]=!0;for(e=0;c=d[e];e++)a in f.requires||(f.requires[a]={}),f.requires[a][c]=!0}};
b.useStrictRequires=!1;b.ENABLE_DEBUG_LOADER=!0;b.require=function(){};b.basePath="";b.nullFunction=function(){};b.identityFunction=function(a){return a};b.abstractMethod=function(){throw Error("unimplemented abstract method");};b.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;b.DEBUG&&(b.instantiatedSingletons_[b.instantiatedSingletons_.length]=a);return a.instance_=new a}};b.instantiatedSingletons_=[];b.DEPENDENCIES_ENABLED=!1;
b.DEPENDENCIES_ENABLED&&(b.included_={},b.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},b.inHtmlDocument_=function(){var a=b.global.document;return"undefined"!=typeof a&&"write"in a},b.findBasePath_=function(){if(b.global.CLOSURE_BASE_PATH)b.basePath=b.global.CLOSURE_BASE_PATH;else if(b.inHtmlDocument_())for(var a=b.global.document.getElementsByTagName("script"),c=a.length-1;0<=c;--c){var d=a[c].src,e=d.lastIndexOf("?"),e=-1==e?d.length:e;if("base.js"==d.substr(e-
7,7)){b.basePath=d.substr(0,e-7);break}}},b.importScript_=function(a){var c=b.global.CLOSURE_IMPORT_SCRIPT||b.writeScriptTag_;!b.dependencies_.written[a]&&c(a)&&(b.dependencies_.written[a]=!0)},b.writeScriptTag_=function(a){if(b.inHtmlDocument_()){var c=b.global.document;if("complete"==c.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}c.write('<script type="text/javascript" src="'+a+'">\x3c/script>');return!0}return!1},b.writeScripts_=function(){function a(f){if(!(f in
e.written)){if(!(f in e.visited)&&(e.visited[f]=!0,f in e.requires))for(var g in e.requires[f])if(!b.isProvided_(g))if(g in e.nameToPath)a(e.nameToPath[g]);else throw Error("Undefined nameToPath for "+g);f in d||(d[f]=!0,c.push(f))}}var c=[],d={},e=b.dependencies_,f;for(f in b.included_)e.written[f]||a(f);for(f=0;f<c.length;f++)if(c[f])b.importScript_(b.basePath+c[f]);else throw Error("Undefined script input");},b.getPathFromDeps_=function(a){return a in b.dependencies_.nameToPath?b.dependencies_.nameToPath[a]:
null},b.findBasePath_(),b.global.CLOSURE_NO_DEPS||b.importScript_(b.basePath+"deps.js"));
b.typeOf=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};b.isDef=function(a){return void 0!==a};b.isNull=function(a){return null===a};b.isDefAndNotNull=function(a){return null!=a};b.isArray=function(a){return"array"==b.typeOf(a)};b.isArrayLike=function(a){var c=b.typeOf(a);return"array"==c||"object"==c&&"number"==typeof a.length};b.isDateLike=function(a){return b.isObject(a)&&"function"==typeof a.getFullYear};b.isString=function(a){return"string"==typeof a};
b.isBoolean=function(a){return"boolean"==typeof a};b.isNumber=function(a){return"number"==typeof a};b.isFunction=function(a){return"function"==b.typeOf(a)};b.isObject=function(a){var c=typeof a;return"object"==c&&null!=a||"function"==c};b.getUid=function(a){return a[b.UID_PROPERTY_]||(a[b.UID_PROPERTY_]=++b.uidCounter_)};b.hasUid=function(a){return!!a[b.UID_PROPERTY_]};b.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(b.UID_PROPERTY_);try{delete a[b.UID_PROPERTY_]}catch(c){}};
b.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);b.uidCounter_=0;b.getHashCode=b.getUid;b.removeHashCode=b.removeUid;b.cloneObject=function(a){var c=b.typeOf(a);if("object"==c||"array"==c){if(a.clone)return a.clone();var c="array"==c?[]:{},d;for(d in a)c[d]=b.cloneObject(a[d]);return c}return a};b.bindNative_=function(a,c,d){return a.call.apply(a.bind,arguments)};
b.bindJs_=function(a,c,d){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(c,d)}}return function(){return a.apply(c,arguments)}};b.bind=function(a,c,d){b.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?b.bindNative_:b.bindJs_;return b.bind.apply(null,arguments)};
b.partial=function(a,c){var d=Array.prototype.slice.call(arguments,1);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(this,c)}};b.mixin=function(a,c){for(var d in c)a[d]=c[d]};b.now=b.TRUSTED_SITE&&Date.now||function(){return+new Date};
b.globalEval=function(a){if(b.global.execScript)b.global.execScript(a,"JavaScript");else if(b.global.eval)if(null==b.evalWorksForGlobals_&&(b.global.eval("var _et_ = 1;"),"undefined"!=typeof b.global._et_?(delete b.global._et_,b.evalWorksForGlobals_=!0):b.evalWorksForGlobals_=!1),b.evalWorksForGlobals_)b.global.eval(a);else{var c=b.global.document,d=c.createElement("script");d.type="text/javascript";d.defer=!1;d.appendChild(c.createTextNode(a));c.body.appendChild(d);c.body.removeChild(d)}else throw Error("goog.globalEval not available");
};b.evalWorksForGlobals_=null;b.getCssName=function(a,c){var d=function(a){return b.cssNameMapping_[a]||a},e=function(a){a=a.split("-");for(var c=[],e=0;e<a.length;e++)c.push(d(a[e]));return c.join("-")},e=b.cssNameMapping_?"BY_WHOLE"==b.cssNameMappingStyle_?d:e:function(a){return a};return c?a+"-"+e(c):e(a)};b.setCssNameMapping=function(a,c){b.cssNameMapping_=a;b.cssNameMappingStyle_=c};
b.getMsg=function(a,c){var d=c||{},e;for(e in d){var f=(""+d[e]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f)}return a};b.getMsgWithFallback=function(a){return a};b.exportSymbol=function(){b.exportPath_("google.ime.l10n.Messages",b.ime.l10n.Messages,void 0)};b.exportProperty=function(a,c,d){a[c]=d};b.inherits=function(a,c){function d(){}d.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new d;a.prototype.constructor=a};
b.base=function(a,c,d){var e=arguments.callee.caller;if(b.DEBUG&&!e)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.superClass_)return e.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),h=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[c]===e)h=!0;else if(h)return g.prototype[c].apply(a,
f);if(a[c]===e)return a.constructor.prototype[c].apply(a,f);throw Error("goog.base called from a method of one name to a method of a different name");};b.scope=function(a){a.call(b.global)};b.MODIFY_FUNCTION_PROTOTYPES=!0;
b.MODIFY_FUNCTION_PROTOTYPES&&(Function.prototype.bind=Function.prototype.bind||function(a,c){if(1<arguments.length){var d=Array.prototype.slice.call(arguments,1);d.unshift(this,a);return b.bind.apply(null,d)}return b.bind(this,a)},Function.prototype.partial=function(a){var c=Array.prototype.slice.call(arguments);c.unshift(this,null);return b.bind.apply(null,c)},Function.prototype.inherits=function(a){b.inherits(this,a)},Function.prototype.mixin=function(a){b.mixin(this.prototype,a)});b.ime={};b.ime.l10n={};b.ime.l10n.Messages={};b.ime.l10n.Messages.MSG_SWISS_GERMAN="Alem\u00e1n de Suiza";b.ime.l10n.Messages.MSG_PHONETIC="Fon\u00e9tico";b.ime.l10n.Messages.MSG_EASTERN="Oriental";b.ime.l10n.Messages.MSG_WESTERN="Occidental";b.ime.l10n.Messages.MSG_LATIN="Lat\u00edn";b.ime.l10n.Messages.MSG_BRAZILIAN="Brasile\u00f1o";b.ime.l10n.Messages.MSG_EUROPEAN="Europeo";b.ime.l10n.Messages.MSG_PRIMARY="Principal";b.ime.l10n.Messages.MSG_SECONDARY="Secundario";
b.ime.l10n.Messages.MSG_CYRILLIC="Cir\u00edlico";b.ime.l10n.Messages.MSG_SIMPLIFIED="Simplificado";b.ime.l10n.Messages.MSG_TRADITIONAL="Tradicional";b.ime.l10n.Messages.MSG_WUBI="Wubi";b.ime.l10n.Messages.MSG_ZHUYIN="Zhuyin";b.ime.l10n.Messages.MSG_CANGJIE="Cangjie";b.ime.l10n.Messages.MSG_CANTONESE="Canton\u00e9s";b.ime.l10n.Messages.MSG_PINYIN="Pinyin";b.ime.l10n.Messages.MSG_HANDWRITE="Escritura t\u00e1ctil";b.ime.l10n.Messages.MSG_US_I18N="Internacional de Estados Unidos";b.exportSymbol();
