#!/bin/sh
MGC_HOME=/usr/local/mentor/ixl_cal_2013.2_18.13 ; export MGC_HOME
$MGC_HOME/bin/calibre -gui -drc -drcLayoutPaths $SC_filter/default.group/layout.views/BUFFER/BUFFER.cal/.BUFFER.bin -drcResultsFile $SC_filter/default.group/layout.views/BUFFER/BUFFER.cal/BUFFER.drc.results -drcLayoutPrimary BUFFER -runset $SC_filter/default.group/layout.views/BUFFER/IMEC.drc.runset -cmnRunHier 0 -batch  > /home/dlavila/puc_thesis/sc_ic/giggity.proj/SC_filter.lib/default.group/layout.views/BUFFER/BUFFER.cal/drc.log
result_count=`grep "TOTAL RESULTS" /home/dlavila/puc_thesis/sc_ic/giggity.proj/SC_filter.lib/default.group/layout.views/BUFFER/BUFFER.cal/drc.log | awk '{ print $6 }'`
if [ "$result_count" = "" ]; then
result_count=-1
fi
MGC_HOME=/usr/local/mentor/2008.2b_linux_x86_64/icflow_home ; export MGC_HOME
$MGC_HOME/bin/send2ic 9189 calibre_drc_done_rve /home/dlavila/puc_thesis/sc_ic/giggity.proj/SC_filter.lib/default.group/layout.views/BUFFER/BUFFER /home/dlavila/puc_thesis/sc_ic/giggity.proj/SC_filter.lib/default.group/layout.views/BUFFER/BUFFER.cal $result_count
